[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Unity Utils"
authors = [{name = "mydimons", email = "mydimons.kb@gmail.com"}]
dynamic = ["version", "description"]
